config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "schools#index"

    resources :schools do
      resources :posts do
        resources :comments
      end
    end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user, optional: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :school
  belongs_to :user, optional: true
  has_many :comments

  validates :title, presence: true
  validates :content, presence: true
end

app/models/school.rb
class School < ApplicationRecord
  has_many :posts
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :posts
has_many :comments

validates :username, presence: true
validates :first_name, presence: true
validates :last_name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from ActiveRecord::RecordNotFound, with: :couldnt_find_record

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

   protected

   def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username])
   end

   private
  def couldnt_find_record
    redirect_to root_url, notice: "That record doesn't exist!"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def new
    @school = School.find(params[:school_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @school = School.find(params[:school_id])
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create!(comment_params.merge(user: current_user))

    redirect_to school_post_path(@school, @post)
  end

  def show
    @school = School.find(params[:school_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def edit
    @school = School.find(params[:school_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @school = School.find(params[:school_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])

    @comment.update(comment_params)
        redirect_to school_post_comment_path(@school, @post, @comment)
  end

  def destroy
    @school = school.find(params[:school_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    rediret_to school_post_path(@school, @post)
  end
end

private
  def comment_params
    params.require(:comment).permit(:commentor, :text)
  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all
  end

  def new
    @school = School.find(params[:school_id])
    @post = Post.new
  end

  def create
    @school = School.find(params[:school_id])
    @post = @school.posts.create!(post_params.merge(user: current_user))

    redirect_to school_path(@school, @posts), notice: "Your post was created!"

  end

  def show
    @school = School.find(params[:school_id])
    @post = Post.find(params[:id])
  end

  def edit
    @school = School.find(params[:school_id])
    @post = Post.find(params[:id])

  end


  def update
    @school = School.find(params[:school_id])
    @post = Post.find(params[:id])
        if @post.user == current_user
          @post.update(post_params)

        else
          flash[:alert] = "Only the author of the post can edit/delete"
        end
        redirect_to school_post_path(@school, @post), notice: "Your post was updated!"
  end

  def destroy
    @school = School.find(params[:school_id])
    @post =  Post.find(params[:id])
    if @post.user == current_user
       @post.destroy
       flash[:alert] = "You post was deleted successfully!"
    else
      flash[:alert] = "Only the author of this post can delete."
    end
    redirect_to school_path(@school)
  end
end

private
  def post_params
    params.require(:post).permit(:author, :title, :content)
  end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController

before_action :authenticate_user!, except: [:index, :show]

  def index
    @schools = School.all
  end

  def new
    @school = School.new
  end

  def create
    @school = School.create!(school_params)
          redirect_to "/schools/"
  end

  def edit
      @school = School.find(params[:id])
  end

  def update
      @school = School.find(params[:id])
      @school.update(school_params)
        redirect_to school_path(@school)
  end

  def show
    @school = School.find(params[:id])
  end

  def destroy
          @school = School.find(params[:id])
          @school.destroy
          redirect_to schools_path
  end
end

private
  def schools_params
    params.require(:school).permit(:name, :city, :state, :url, :img_url)
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>
<!-- <nav>
  <%= link_to "Home", schools_path%>
  <% if !current_user %>
      <%= link_to "Sign Up", new_user_registration_path %>
      <%= link_to "Login", new_user_session_path %>
  <%else%>
      <%= link_to "Log Out", destroy_user_session_path, :method => :delete %>
  <% end %>

</nav> -->

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h2>Create a Comment for This Post</h2>
<div class="postwithcare">
  <p>Comment with care.... comments cannot be removed! </p>
  <p>Once it's out there, it's out there!</p>
  <a href="http://s4.photobucket.com/user/Kowulz/media/NoTrollsAni.gif.html" target="_blank"><img src="http://i4.photobucket.com/albums/y115/Kowulz/NoTrollsAni.gif" border="0" alt="No Trolls Ani photo NoTrollsAni.gif"></a>
</div>

<%= form_for [@school, @post, @comment] do |f|%>

  <div class="container">
  <%=f.label :comment %><br>
  <%=f.text_area :text, size: "50x10" %>
  </div>

  <%= f.submit "Create"%>
<%end%>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>POSTGrad</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Graduate" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="jumbotron.css" rel="stylesheet">
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="assets/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>
    <div class="container">
          <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container-fluid">
            <div class="navbar-header">
              <!-- <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button> -->
              <a class="navbar-brand" href="/">POSTGrad</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
              <ul class="nav navbar-nav navbar-right">
                <li><a href="/">Home</a></li>
                  <% if !current_user %>
                      <li><%= link_to "Sign Up", new_user_registration_path %></li>
                      <li><%= link_to "Login", new_user_session_path %></li>
                  <%else%>
                      <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
                  <% end %>
              </ul>
            </div>
          </div>
        </nav>

        <div class="container">
            <p class="notice"><%= notice %></p>
            <p class="alert"><%= alert %></p>
        </div>

<%= yield %>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
  </body>

</html>

app/views/posts/edit.html.erb
<h1>Edit This Post</h1>

<%= form_for [@school, @post] do |f|%>

  <%=f.label :post_title %><br>
  <%=f.text_area :title, size: "50x1" %>
<div class="container">
  <%=f.label :content %><br>
  <%=f.text_area :content, size: "50x10" %>
</div>
  <%= f.submit "Update"%>
<%end%>

<%= form_for [@school, @post], method: :delete do |f| %>
  <%= f.submit "Delete this Post!", class: "delete" %>
<% end %>

app/views/posts/new.html.erb
<h2>Create a Post for Your School</h2>


<%= form_for [@school, @post] do |f|%>

  <%=f.label :post_title %><br>
  <%=f.text_area :title, size: "50x1" %>
<div class="container">
  <%=f.label :content %><br>
  <%=f.text_area :content, size: "50x10" %>
</div>
  <%= f.submit "Create"%>
<%end%>

app/views/posts/show.html.erb
<% flash.each do |type, message| %>
  <p> <%= message %></p>
    <% end %>
<div class="container">
  <div class="postshow">
      <h1><%= @post.title %></h1>
      <h3>Creator: <%=@post.user[:username]%></h3>
        <%if @post.user == current_user%>
          <p><%= link_to "Edit this Post", edit_school_post_path(@school, @post)%></p>
        <%else%>
        <%end%>

      <p> Created <%=time_ago_in_words(@post.created_at)%> ago</p>

    <div class="container_post">
      <h4><%=@post.content%></h4>
    </div>
  </div>
</div>

  <hr class="featurette-divider">

<h3>Comments</h3>
<p><%= link_to "Comment on This Post", new_school_post_comment_path(@school, @post, @comment)%></p>

  <div class="container">
    <% @post.comments.each do |comment| %>
        <div class="comments">
            <div class="well">
                <div class="commentor">
                    <p><span class="glyphicon glyphicon-user"></span><%=comment.user[:username]%> commeted <%=time_ago_in_words(comment.created_at)%> ago</p>
                </div>
                <p><%=comment.text%>
            </div>
    <%end%>
    </div>
</div>

<hr class="featurette-divider">

app/views/schools/index.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="container">
   <div class="jumbotron">
     <div class="container">
       <div class="schoolindex">
         <h1>POSTGRAD</h1>
         <h3>The Alumni Connection</h3>
         <p>Have an extra ticket to the game? Looking for information on a local alumni chapter? Want to network with graduates from your major? POSTGrad is here to help you connect with alumni from your Alma Mater.</p>
               <select onChange="if(this.selectedIndex!=0) self.location=this.options[this.selectedIndex].value">
                 <option>Select A College/University</option>
                   <% @schools.each do |school| %>
                 <option value="<%= school_path(school) %>"><%= school.name %></option>
                   <% end %>
               </select>
         </div>
     </div>
   </div>
</div>

<hr class="featurette-divider">
<div class="container">
  <div class="row placeholders">
    <h1>Featured Schools</h1>
    <p>Check out some of the universities that are buzzing on POSTGrad</p>
    <hr class="featurette-divider">
          <div class="col-xs-6 col-sm-3 col-md-3 col-lg-3 placeholder">
            <a href="/schools/134">
                <img class ='img-circle' src= "https://www.hastac.org/sites/default/files/upload/images/opportunity/ohio_state_buckeyes.jpg" width="200" height="200" class="img-responsive" alt="Ohio State">
            </a>
                <h4>The Ohio State University</h4>
            <span class="text-muted">Columbus, OH</span>
          </div>
          <div class="col-xs-6 col-sm-3 col-md-3 col-lg-3 placeholder">
            <a href="/schools/79">
              <img class ='img-circle' src= "https://s-media-cache-ak0.pinimg.com/736x/17/4e/3a/174e3a4c323410f37289777ef3318538.jpg" width="200" height="200" class="img-responsive" alt="George Washington University">
            </a>
            <h4>George Washington University</h4>
            <span class="text-muted">Washington, D.C.</span>
          </div>
          <div class="col-xs-6 col-sm-3 col-md-3 col-lg-3 placeholder">
            <a href="/schools/207">
              <img class = 'img-circle' src= "https://s-media-cache-ak0.pinimg.com/originals/ee/31/62/ee31627029d60a73df410207f0d220bf.jpg" width="200" height="200" class="img-responsive" alt="Maryland">
            </a>
            <h4>The University of Maryland</h4>
            <span class="text-muted">College Park, MD</span>
          </div>
          <div class="col-xs-6 col-sm-3 col-md-3 col-lg-3 placeholder">
            <a href="/schools/4">
              <img class ='img-circle' src="http://www.crwflags.com/fotw/images/u/us_au.gif" width="200" height="200" class="img-responsive" alt="American University">
            </a>
            <h4>American University</h4>
            <span class="text-muted">Washington, D.C.</span>
          </div>
        </div>
</div>

<hr class="featurette-divider">

<div class="container">
  <h1>Why <span class="logo">POSTGRAD</span>?</h1>
<hr class="featurette-divider">
  <div class="col-md-7">
    <h2 class="featurette-heading">Network <span class="text-muted">within your school...</span></h2>
    <p class="lead">You know your alma mater has the best grads... why else would you have gone there? Connect and network with other link minded alumni.</p>
  </div>
  <div class="col-md-5">
    <img class="featurette-image img-responsive center-block" src="https://assets.entrepreneur.com/content/3x2/1300/20160328065249-shutterstock-387029653.jpeg" alt="Generic placeholder image">
  </div>
</div>

  <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7 col-md-push-5">
          <h2 class="featurette-heading">Reminisce <span class="text-muted">about the past...</span></h2>
          <p class="lead">Remember and relive the glory days of college. Story tell about your favorite hangouts, a game you will never forget, or instructors who changed your life. Those years were some of your best. </p>
        </div>
        <div class="col-md-5 col-md-pull-7">
          <img class="featurette-image img-responsive center-block" src="http://www.kiplinger.com/slideshow/taxes/T054-S001-overlooked-tax-breaks-for-new-college-grads/images/intro.jpg" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">Connect <span class="text-muted">with the best Alumni...</span></h2>
          <p class="lead">Going to the big game and you have an extra ticket to sell? Heading back to campus and want to know the best new restaurant? Whatever you need to know about your school today, post it!</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive center-block" src="http://assets.inarkansas.com/31388/campus-visit.jpg" alt="Generic placeholder image">
        </div>
      </div>
</div>
      <hr class="featurette-divider">

      <!-- /END THE FEATURETTES -->


      <!-- FOOTER -->
<div class="container">
      <footer>
        <p class="pull-right"><a href="/">Back to top</a></p>
        <p>&copy; 2017 POSTGrad</p>
      </footer>
</div>

app/views/schools/show.html.erb
<div class="container">
    <div class="jumbotron">
        <h1><%= @school.name %></h1>
        <h3>Home of the <%=@school.mascot%></h3>
            <img><%=image_tag (@school.img_url)%></img>
    </div>
</div>

<hr class="featurette-divider">
    <p><%= link_to "Add a Post!", new_school_post_path(@school)%></p>
      <% flash.each do |type, message| %>
        <p> <%= message %></p>
          <% end %>
<hr class="featurette-divider">

<div class="container">
  <% @school.posts.order(created_at: :DESC).each do |post| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h2 class="panel-title"><%=link_to post.title, school_post_path(@school, post) %></h2>
        <p>Author: <%=post.user[:username]%> | Created <%=time_ago_in_words(post.created_at)%> ago</p>
      </div>
    <div class="panel-body">
      <p class="text"><%=post.content%></p>
    </div>
  </div>
    <a href="/schools/<%=@school.id%>/posts/<%=post.id%>"><p class="btn btn-primary" role="button">View Comments &raquo;</p></a>
    <%end%>
  </div>
</div>

<hr class="featurette-divider">